<a href="https://colab.research.google.com/github/amaansadat/SRDT/blob/main/DataFrame.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
import pandas as pd

In [ ]:
from numpy.random import randn
np.random.seed(101)

In [ ]:
df=pd.DataFrame(randn(5,4),index='A B C D E'.split(),columns='W X Y Z'.split())
df

          W         X         Y         Z
A  2.706850  0.628133  0.907969  0.503826
B  0.651118 -0.319318 -0.848077  0.605965
C -2.018168  0.740122  0.528813 -0.589001
D  0.188695 -0.758872 -0.933237  0.955057
E  0.190794  1.978757  2.605967  0.683509

In [ ]:
df[['X','Y']]

          X         Y
A  0.628133  0.907969
B -0.319318 -0.848077
C  0.740122  0.528813
D -0.758872 -0.933237
E  1.978757  2.605967

In [ ]:
df.W

A    2.706850
B    0.651118
C   -2.018168
D    0.188695
E    0.190794
Name: W, dtype: float64

In [ ]:
type(df['W'])

pandas.core.series.Series

In [ ]:
df['new']=df['W']+df['Y']

In [ ]:
df

          W         X         Y         Z       new
A  2.706850  0.628133  0.907969  0.503826  3.614819
B  0.651118 -0.319318 -0.848077  0.605965 -0.196959
C -2.018168  0.740122  0.528813 -0.589001 -1.489355
D  0.188695 -0.758872 -0.933237  0.955057 -0.744542
E  0.190794  1.978757  2.605967  0.683509  2.796762

In [ ]:
df.drop('new',axis=1)

          W         X         Y         Z
A  2.706850  0.628133  0.907969  0.503826
B  0.651118 -0.319318 -0.848077  0.605965
C -2.018168  0.740122  0.528813 -0.589001
D  0.188695 -0.758872 -0.933237  0.955057
E  0.190794  1.978757  2.605967  0.683509

In [ ]:
df.drop('new',axis=1,inplace=True)
df

KeyError: "['new'] not found in axis"

In [ ]:
#On indexing we get column
#To extract a column we use df.loc['name'] and iloc[indexno.] for index no.
df.loc['A']

W    2.706850
X    0.628133
Y    0.907969
Z    0.503826
Name: A, dtype: float64

In [ ]:
df.iloc[2]

W   -2.018168
X    0.740122
Y    0.528813
Z   -0.589001
Name: C, dtype: float64

In [ ]:
df.loc[['A','B'],['W','Y']]

          W         Y
A  2.706850  0.907969
B  0.651118 -0.848077

In [ ]:
df.iloc[:2,:2]

          W         X
A  2.706850  0.628133
B  0.651118 -0.319318

In [ ]:
#axis=0 is for rows and axis=1 is for columns
df.drop('E',axis=0)

          W         X         Y         Z
A  2.706850  0.628133  0.907969  0.503826
B  0.651118 -0.319318 -0.848077  0.605965
C -2.018168  0.740122  0.528813 -0.589001
D  0.188695 -0.758872 -0.933237  0.955057

In [ ]:
df.loc[['A','C'],['Z','X']]

          Z         X
A  0.503826  0.628133
C -0.589001  0.740122

In [ ]:
df.iloc[['-1','-2']]

          W         X         Y         Z
E  0.190794  1.978757  2.605967  0.683509
D  0.188695 -0.758872 -0.933237  0.955057

In [ ]:
df[df['Y']>0]

          W         X         Y         Z
A  2.706850  0.628133  0.907969  0.503826
C -2.018168  0.740122  0.528813 -0.589001
E  0.190794  1.978757  2.605967  0.683509

In [ ]:
df[df['W']>0]['Z']

A    0.503826
B    0.605965
D    0.955057
E    0.683509
Name: Z, dtype: float64

In [ ]:
df[(df['W']>0)&(df['Y']>1)]

          W         X         Y         Z
E  0.190794  1.978757  2.605967  0.683509

In [ ]:
df

          W         X         Y         Z
A  2.706850  0.628133  0.907969  0.503826
B  0.651118 -0.319318 -0.848077  0.605965
C -2.018168  0.740122  0.528813 -0.589001
D  0.188695 -0.758872 -0.933237  0.955057
E  0.190794  1.978757  2.605967  0.683509

In [ ]:
newind='CA NY WY OR CO'.split()

In [ ]:
df.reset_index()

  index         W         X         Y         Z
0     A  2.706850  0.628133  0.907969  0.503826
1     B  0.651118 -0.319318 -0.848077  0.605965
2     C -2.018168  0.740122  0.528813 -0.589001
3     D  0.188695 -0.758872 -0.933237  0.955057
4     E  0.190794  1.978757  2.605967  0.683509

In [ ]:
df['States']=newind

In [ ]:
df

          W         X         Y         Z States
A  2.706850  0.628133  0.907969  0.503826     CA
B  0.651118 -0.319318 -0.848077  0.605965     NY
C -2.018168  0.740122  0.528813 -0.589001     WY
D  0.188695 -0.758872 -0.933237  0.955057     OR
E  0.190794  1.978757  2.605967  0.683509     CO

In [ ]:
df.set_index('States',inplace=True)

In [ ]:
df

               W         X         Y         Z
States
CA      2.706850  0.628133  0.907969  0.503826
NY      0.651118 -0.319318 -0.848077  0.605965
WY     -2.018168  0.740122  0.528813 -0.589001
OR      0.188695 -0.758872 -0.933237  0.955057
CO      0.190794  1.978757  2.605967  0.683509

In [ ]:
outside=['G1','G1','G1','G2','G2','G2']
inside=[1,2,3,1,2,3]
hier_index=list(zip(outside,inside))
hier_index=pd.MultiIndex.from_tuples(hier_index)

In [ ]:
hier_index

MultiIndex([('G1', 1),
            ('G1', 2),
            ('G1', 3),
            ('G2', 1),
            ('G2', 2),
            ('G2', 3)],
           )

In [ ]:
df=pd.DataFrame(np.random.randn(6,2),index=hier_index,columns=['A','B'])
df

             A         B
G1 1 -0.497104 -0.754070
   2 -0.943406  0.484752
   3 -0.116773  1.901755
G2 1  0.238127  1.996652
   2 -0.993263  0.196800
   3 -1.136645  0.000366

In [ ]:
df.loc['G1'].loc[1]

A   -0.497104
B   -0.754070
Name: 1, dtype: float64

In [ ]:
df.index.names

FrozenList([None, None])

In [ ]:
df.index.names=['Group','Num']
df

                  A         B
Group Num
G1    1   -0.497104 -0.754070
      2   -0.943406  0.484752
      3   -0.116773  1.901755
G2    1    0.238127  1.996652
      2   -0.993263  0.196800
      3   -1.136645  0.000366

In [ ]:
df.xs(1,level='Roll')

KeyError: 'Level Roll not found'

In [ ]:
#MISSING DATA

In [ ]:
import numpy as np
import pandas as pd
df=pd.DataFrame({'A':[1,2,np.nan],'B':[5,np.nan,np.nan],'C':[1,2,3]})
df

     A    B  C
0  1.0  5.0  1
1  2.0  NaN  2
2  NaN  NaN  3

In [ ]:
df.describe()

              A    B    C
count  2.000000  1.0  3.0
mean   1.500000  5.0  2.0
std    0.707107  NaN  1.0
min    1.000000  5.0  1.0
25%    1.250000  5.0  1.5
50%    1.500000  5.0  2.0
75%    1.750000  5.0  2.5
max    2.000000  5.0  3.0

In [ ]:
df.columns

Index(['A', 'B', 'C'], dtype='object')

In [ ]:
df.isnull()

       A      B      C
0  False  False  False
1  False   True  False
2   True   True  False

In [ ]:
df.dropna(axis=1)

   C
0  1
1  2
2  3

In [ ]:
df

     A    B  C
0  1.0  5.0  1
1  2.0  NaN  2
2  NaN  NaN  3

In [ ]:
#if we don't give any axis then conventionally it'll remove rows i.e axis=0

df.dropna(thresh=1)

     A    B  C
0  1.0  5.0  1
1  2.0  NaN  2
2  NaN  NaN  3

In [ ]:
df.fillna(value=5)

     A    B  C
0  1.0  5.0  1
1  2.0  5.0  2
2  5.0  5.0  3

In [ ]:
df['A'].fillna(value=df['A'].mean())

0    1.0
1    2.0
2    1.5
Name: A, dtype: float64

In [ ]:
df['B'].fillna(value=df['B'].mean())

0    5.0
1    5.0
2    5.0
Name: B, dtype: float64

In [ ]:
df['B'].fillna(value=df['C'].mean())

0    5.0
1    2.0
2    2.0
Name: B, dtype: float64

In [ ]:
df.rename(columns={'A':'Alpha','B':'Beta'})

   Alpha  Beta  C
0    1.0   5.0  1
1    2.0   NaN  2
2    NaN   NaN  3