<a href="https://colab.research.google.com/github/amaansadat/SRDT/blob/main/Pandas.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
import pandas as pd

In [ ]:
labels=['a','b','c']
mylist=[10,20,30]
arr=np.array([10,20,30])
d={'a':10,'b':20,'c':30}

In [ ]:
pd.Series(data=mylist)

0    10
1    20
2    30
dtype: int64

In [ ]:
pd.Series(index=labels,data=mylist)

a    10
b    20
c    30
dtype: int64

In [ ]:
pd.Series(mylist,labels)

a    10
b    20
c    30
dtype: int64

In [ ]:
pd.Series(data=arr,index=labels)

a    10
b    20
c    30
dtype: int64

In [ ]:
pd.Series(d)

a    10
b    20
c    30
dtype: int64

In [ ]:
sl=pd.Series([sum,print,len])

In [ ]:
sl

0      <built-in function sum>
1    <built-in function print>
2      <built-in function len>
dtype: object

In [ ]:
sl[1]([1,2,3,4,5,6,7,8])

[1, 2, 3, 4, 5, 6, 7, 8]

In [ ]:
ser1=pd.Series([1,2,5,4],index=['USA','Germany','Italy','Japan'])
ser1

USA        1
Germany    2
Italy      5
Japan      4
dtype: int64

In [ ]:
ser2=pd.Series([1,2,3,4],index=['USA','Germany','USSR','Japan'])
ser2

USA        1
Germany    2
USSR       3
Japan      4
dtype: int64

In [ ]:
ser1+ser2

Germany    4.0
Italy      NaN
Japan      8.0
USA        2.0
USSR       NaN
dtype: float64

In [ ]:
ser1-ser2

Germany    0.0
Italy      NaN
Japan      0.0
USA        0.0
USSR       NaN
dtype: float64

In [ ]:
ser1/ser2

Germany    1.0
Italy      NaN
Japan      1.0
USA        1.0
USSR       NaN
dtype: float64

In [ ]:
ser1*2

USA         2
Germany     4
Italy      10
Japan       8
dtype: int64